# This file was generated by roxyPackage::roxy.package()
# and will likely be overwritten on its next run.
# Editing is futile.

#' \packageDescription{XiMpLe}
#'
#' The DESCRIPTION file:
#' \tabular{ll}{
#' Package: \tab XiMpLe\cr
#' Type: \tab Package\cr
#' Version: \tab 0.11-3\cr
#' Date: \tab 2024-07-18\cr
#' Depends: \tab R (>= 3.0.0)\cr
#' Encoding: \tab UTF-8\cr
#' License: \tab GPL (>= 3)\cr
#' LazyLoad: \tab yes\cr
#' URL: \tab https://reaktanz.de/?c=hacking&s=XiMpLe\cr
#' }
#'
#' @title
#' \packageTitle{XiMpLe}
#' @author
#' \packageAuthor{XiMpLe}
#'
#' Maintainer: \packageMaintainer{XiMpLe}
"_PACKAGE"

## usethis namespace: start
## usethis namespace: end
NULL